# Generated by Django 5.1.1 on 2024-09-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0035_accountnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionfour',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactionone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactionthree',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactiontwo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transactionfive',
        ),
        migrations.DeleteModel(
            name='Transactionfour',
        ),
        migrations.DeleteModel(
            name='Transactionone',
        ),
        migrations.DeleteModel(
            name='Transactionthree',
        ),
        migrations.DeleteModel(
            name='Transactiontwo',
        ),
    ]
