# Generated by Django 5.1.1 on 2024-09-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0036_remove_transactionfour_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemcard',
            name='card_name',
            field=models.CharField(default='Amazon Gift Card', max_length=200, null=True),
        ),
    ]
