# Generated by Django 5.1.1 on 2024-09-17 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0037_redeemcard_card_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('accountnumber', models.CharField(default='-', max_length=200)),
                ('currency', models.CharField(default='-', max_length=200)),
                ('note', models.TextField(default='-', max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('charge', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='Pending...', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
