# Generated by Django 5.1.1 on 2024-09-17 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0041_banktransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('depositplan', models.CharField(default='-', max_length=200)),
                ('currency', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('remark', models.TextField(max_length=200)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(default='Pending...', max_length=200)),
                ('returnamount', models.CharField(max_length=200)),
                ('time', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
