# Generated by Django 5.1.1 on 2024-09-17 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0044_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='accountname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='accountnumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='bankname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='note',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='currency',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='depositplan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='action',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='active_loans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_to_pay',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='next_payment_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='accountnumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='charge',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='currency',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='note',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wiretransfer',
            name='accountname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wiretransfer',
            name='accountnumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wiretransfer',
            name='amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wiretransfer',
            name='bankname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wiretransfer',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wiretransfer',
            name='note',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wiretransfer',
            name='swiftcode',
            field=models.TextField(max_length=200),
        ),
    ]
