# Generated by Django 5.1.1 on 2024-09-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0045_alter_banktransfer_accountname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='amount',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
