# Generated by Django 5.1.1 on 2024-09-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0046_transfer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='status',
            field=models.CharField(default='Pending...', max_length=200),
        ),
        migrations.AddField(
            model_name='wiretransfer',
            name='status',
            field=models.CharField(default='Pending...', max_length=200),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='currency',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='charge',
            field=models.CharField(default='-10', max_length=200),
        ),
        migrations.AlterField(
            model_name='wiretransfer',
            name='currency',
            field=models.CharField(max_length=200),
        ),
    ]
