# Generated by Django 5.1.1 on 2024-09-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0047_banktransfer_status_wiretransfer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='status',
            field=models.CharField(choices=[('Pending...', 'Pending...'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending...', max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('Pending...', 'Pending...'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending...', max_length=200),
        ),
        migrations.AlterField(
            model_name='wiretransfer',
            name='status',
            field=models.CharField(choices=[('Pending...', 'Pending...'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending...', max_length=200),
        ),
    ]
