# Generated by Django 5.1.1 on 2024-09-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0049_remove_deposit_euro_remove_deposit_inr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='notification_message',
            field=models.CharField(max_length=200),
        ),
    ]
