# Generated by Django 5.1.1 on 2024-09-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0050_alter_deposit_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verify',
            field=models.CharField(default='yes', max_length=200, null=True),
        ),
    ]
