# Generated by Django 5.1.1 on 2024-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0051_customer_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnumber',
            name='account',
            field=models.CharField(default='Generating Account Number....', max_length=200),
        ),
    ]
